version: '3.3'

services:
  postgres:
    container_name: postgres_guac
    image: postgres:latest
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      POSTGRES_DB: guacamole_db

  guacd:
    container_name: guacd_guac
    image: guacamole/guacd:latest
    restart: always
    ports: 
      - "4822:4822"

  guacamole:
    container_name: guacamole_guac
    image: guacamole/guacamole:latest
    restart: always
    ports:
      - "10011:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
    depends_on:
      - postgres
      - guacd

